package internal

type itemMap map[string]int

// Weapons is a map of in-game weapons with their corresponding IDs
var Weapons = itemMap{
	"none":                    0,
	"revolver":                1,
	"triple machinegun":       2,
	"wrench":                  3,
	"machinegun":              4,
	"shotgun":                 5,
	"crossbow":                6,
	"grenade launcher":        7,
	"double shotgun":          8,
	"minigun":                 9,
	"auto shotgun":            10,
	"auto crossbow":           11,
	"super crossbow":          12,
	"shovel":                  13,
	"bazooka":                 14,
	"sticky launcher":         15,
	"smg":                     16,
	"assault rifle":           17,
	"disc gun":                18,
	"laser pistol":            19,
	"laser rifle":             20,
	"slugger":                 21,
	"gatling slugger":         22,
	"assault slugger":         23,
	"energy sword":            24,
	"super slugger":           25,
	"hyper rifle":             26,
	"screwdriver":             27,
	"laser minigun":           28,
	"blood launcher":          29,
	"splinter gun":            30,
	"toxic bow":               31,
	"sentry gun":              32,
	"wave gun":                33,
	"plasma gun":              34,
	"plasma cannon":           35,
	"energy hammer":           36,
	"jackhammer":              37,
	"flak cannon":             38,
	"golden revolver":         39,
	"golden wrench":           40,
	"golden machinegun":       41,
	"golden shotgun":          42,
	"golden crossbow":         43,
	"golden grenade launcher": 44,
	"golden laser pistol":     45,
	"chicken sword":           46,
	"nuke launcher":           47,
	"ion cannon":              48,
	"quadruple machinegun":    49,
	"flamethrower":            50,
	"dragon":                  51,
	"flare gun":               52,
	"energy screwdriver":      53,
	"hyper launcher":          54,
	"laser cannon":            55,
	"rusty revolver":          56,
	"lightning pistol":        57,
	"lightning rifle":         58,
	"lightning shotgun":       59,
	"super flak cannon":       60,
	"sawed off shotgun":       61,
	"splinter pistol":         62,
	"super splinter gun":      63,
	"lightning smg":           64,
	"smart gun":               65,
	"heavy crossbow":          66,
	"blood hammer":            67,
	"lightning cannon":        68,
	"pop gun":                 69,
	"plasma rifle":            70,
	"pop rifle":               71,
	"toxic launcher":          72,
	"flame cannon":            73,
	"lightning hammer":        74,
	"flame shotgun":           75,
	"double flame shotgun":    76,
	"auto flame shotgun":      77,
	"cluster launcher":        78,
	"grenade shotgun":         79,
	"grenade rifle":           80,
	"rogue rifle":             81,
	"party gun":               82,
	"double minigun":          83,
	"gatling bazooka":         84,
	"auto grenade shotgun":    85,
	"ultra revolver":          86,
	"ultra laser pistol":      87,
	"sledgehammer":            88,
	"heavy revolver":          89,
	"heavy machinegun":        90,
	"heavy slugger":           91,
	"ultra shovel":            92,
	"ultra shotgun":           93,
	"ultra crossbow":          94,
	"ultra grenade launcher":  95,
	"plasma minigun":          96,
	"devastator":              97,
	"golden plasma gun":       98,
	"golden slugger":          99,
	"golden splinter gun":     100,
	"golden screwdriver":      101,
	"golden bazooka":          102,
	"golden assault rifle":    103,
	"super disc gun":          104,
	"heavy auto crossbow":     105,
	"heavy assault rifle":     106,
	"blood cannon":            107,
	"dog spin attack":         108,
	"dog missile":             109,
	"incinerator":             110,
	"super plasma cannon":     111,
	"seeker pistol":           112,
	"seeker shotgun":          113,
	"eraser":                  114,
	"guitar":                  115,
	"bouncer smg":             116,
	"bouncer shotgun":         117,
	"hyper slugger":           118,
	"super bazooka":           119,
	"frog pistol":             120,
	"black sword":             121,
	"golden nuke launcher":    122,
	"golden disc gun":         123,
	"heavy grenade launcher":  124,
	"gun gun":                 125,
	"eggplant":                126,
	"golden frog pistol":      127,
}

// Mutations is a map of in-game mutations with their corresponding IDs
var Mutations = itemMap{
	"none":              0,
	"rhino skin":        1,
	"extra feet":        2,
	"plutonium hunger":  3,
	"rabbit paw":        4,
	"throne butt":       5,
	"lucky shot":        6,
	"bloodlust":         7,
	"gamma guts":        8,
	"second stomach":    9,
	"back muscle":       10,
	"scarier face":      11,
	"euphoria":          12,
	"long arms":         13,
	"boiling veins":     14,
	"shotgun shoulders": 15,
	"recycle gland":     16,
	"laser brain":       17,
	"last wish":         18,
	"eagle eyes":        19,
	"impact wrists":     20,
	"bolt marrow":       21,
	"stress":            22,
	"trigger fingers":   23,
	"sharp teeth":       24,
	"patience":          25,
	"hammerhead":        26,
	"strong spirit":     27,
	"open mind":         28,
	"heavy heart":       29,
}

// Chars is a map of in-game characters and their corresponding IDs
var Chars = itemMap{
	"random":   0,
	"fish":     1,
	"crystal":  2,
	"eyes":     3,
	"melting":  4,
	"plant":    5,
	"venuz":    6,
	"steroids": 7,
	"robot":    8,
	"chicken":  9,
	"rebel":    10,
	"horror":   11,
	"rogue":    12,
	"bigdog":   13,
	"skeleton": 14,
	"frog":     15,
}

// Crowns is a map of in-game crowns with their corresponding IDs
var Crowns = itemMap{
	"random":     0,
	"none":       1,
	"death":      2,
	"life":       3,
	"haste":      4,
	"guns":       5,
	"hatred":     6,
	"blood":      7,
	"destiny":    8,
	"love":       9,
	"luck":       10,
	"curses":     11,
	"risk":       12,
	"protection": 13,
}

// NameToID returns the ID of the thing
func (m itemMap) NameToID(name string) int {
	if i, ok := m[name]; ok {
		return i
	}
	return -1
}

// IDToName returns the name of the ID
func (m itemMap) IDToName(id int) string {
	for k, v := range m {
		if v == id {
			return k
		}
	}
	return ""
}
